# Custom Language File for Launcher Customizer

[ejs.app]
title = "Lantern Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/kalitsune/LanternLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/Ye2FesBVEm"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE LANTERN LAUNCHER"
welcomeDescription = ""
welcomeDescCTA = "You are just a few clicks away from the Cosmic Fox Network."
