name: Build

#build on tag starting with lv
on:
  push:
    tags:
      - 'v*-L'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    needs: release

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Checkout the commit from release job
        run: |
          git fetch origin ${{ needs.release.outputs.commit_sha }} --depth=1
          git checkout ${{ needs.release.outputs.commit_sha }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          release: true
    
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}

    outputs:
      commit_sha: ${{ steps.update_version.outputs.commit_sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ env.VERSION }}
      
      - name: Commit files
        id: update_version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "🏷️ bumping release ${{ env.VERSION }}"
          echo "::set-output name=commit_sha::$(git rev-parse HEAD)"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}

      - name: Github Automatic Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false